version: '3.8'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - SECRET_KEY=%#l%d+#58)%#d1oopq3l=xf_&x+w98-t$$)p1l11nav@kdgu&2k
      - DEBUG=True
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - STRIPE_PUBLIC_KEY=pk_test_51LrFbSAKDXn8icjFp0ey8Ji8imSPcER1Gr6dNihiqrt7WvdXF98y8f8DwOHgKdGAFCIRJlFr52KnlCyzfPvOQljX00ZtWh74Gd
      - STRIPE_SECRET_KEY=sk_test_51LrFbSAKDXn8icjFLc1Wtc2GtYAbmbAW983SlLMcVUjbtTDfrxPoxdoqF7iyWBHAjJ5FujiGcR46adb3B1IvDBhF00gkfc8O7r
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

